import type { NextPage } from 'next'
import { useSession } from 'next-auth/react';
import Head from 'next/head'

const Home: NextPage = () => {
  const { data : session } = useSession();
  return (
    <div className="bg-amber-50 h-screen w-screen">
      <Head>
            <title>내가 만든 세상 - test</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
         인덱스
        
      </main>

      {/* <footer className={styles.footer}>
      
      </footer> */}
    </div>
  )
}

export default Home
